# Generated by Django 2.1.1 on 2018-10-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('gender', models.IntegerField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
