# Generated by Django 2.1.1 on 2018-10-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_database', '0002_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
