# Generated by Django 2.1.1 on 2018-10-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_database', '0006_auto_20181013_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
